//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAFRANFER_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inscripcion_detalle
    {
        public int inscripcion_id { get; set; }
        public int inscripcion_det_id { get; set; }
        public int curso_id { get; set; }
        public decimal precio { get; set; }
        public decimal subtotal { get; set; }
    }
}
