//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAFRANFER_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inscripcion
    {
        public int inscripcion_id { get; set; }
        public int estudiante_id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<decimal> importe { get; set; }
        public string estado { get; set; }
        public string observacion { get; set; }
    }
}
